EbsTisbiBook.WebAppMVC/Areas/Admin/Controllers/FgosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EbsTisbiBook.WebAppMVC.Models;
using EbsTisbiBook.WebAppMVC.Models.Library;
using Microsoft.AspNetCore.Authorization;

namespace EbsTisbiBook.WebAppMVC.Controllers.Admin
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class FgosController : Controller
    {
        private readonly LibraryContext _context;

        public FgosController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Fgos
        public async Task<IActionResult> Index()
        {
            var libraryContext = _context.Fgos.Include(f => f.Ugnp);
            return View(await libraryContext.ToListAsync());
        }

        // GET: Fgos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fgos = await _context.Fgos
                .Include(f => f.Ugnp)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fgos == null)
            {
                return NotFound();
            }

            return View(fgos);
        }

        // GET: Fgos/Create
        public IActionResult Create()
        {
            ViewData["UgnpId"] = new SelectList(_context.Ugnp, "Id", "Name");
            return View();
        }

        // POST: Fgos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UgnpId")] Fgos fgos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fgos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UgnpId"] = new SelectList(_context.Ugnp, "Id", "Name", fgos.UgnpId);
            return View(fgos);
        }

        // GET: Fgos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fgos = await _context.Fgos.FindAsync(id);
            if (fgos == null)
            {
                return NotFound();
            }
            ViewData["UgnpId"] = new SelectList(_context.Ugnp, "Id", "Name", fgos.UgnpId);
            return View(fgos);
        }

        // POST: Fgos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UgnpId")] Fgos fgos)
        {
            if (id != fgos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fgos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FgosExists(fgos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UgnpId"] = new SelectList(_context.Ugnp, "Id", "Name", fgos.UgnpId);
            return View(fgos);
        }

        // GET: Fgos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fgos = await _context.Fgos
                .Include(f => f.Ugnp)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fgos == null)
            {
                return NotFound();
            }

            return View(fgos);
        }

        // POST: Fgos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fgos = await _context.Fgos.FindAsync(id);
            _context.Fgos.Remove(fgos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FgosExists(int id)
        {
            return _context.Fgos.Any(e => e.Id == id);
        }
    }
}

EbsTisbiBook.WebAppMVC/Areas/Admin/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using EbsTisbiBook.WebAppMVC.Models.Identity;
using EbsTisbiBook.WebAppMVC.Models.Identity.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace EbsTisbiBook.WebAppMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

EbsTisbiBook.WebAppMVC/Areas/Admin/Controllers/UgnpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EbsTisbiBook.WebAppMVC.Models;
using EbsTisbiBook.WebAppMVC.Models.Library;
using Microsoft.AspNetCore.Authorization;

namespace EbsTisbiBook.WebAppMVC.Controllers.Admin
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UgnpController : Controller
    {
        private readonly LibraryContext _context;

        public UgnpController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Ugnps
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ugnp.ToListAsync());
        }

        // GET: Ugnps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ugnp = await _context.Ugnp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ugnp == null)
            {
                return NotFound();
            }

            return View(ugnp);
        }

        // GET: Ugnps/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ugnps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Ugnp ugnp)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ugnp);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ugnp);
        }

        // GET: Ugnps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ugnp = await _context.Ugnp.FindAsync(id);
            if (ugnp == null)
            {
                return NotFound();
            }
            return View(ugnp);
        }

        // POST: Ugnps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Ugnp ugnp)
        {
            if (id != ugnp.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ugnp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UgnpExists(ugnp.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ugnp);
        }

        // GET: Ugnps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ugnp = await _context.Ugnp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ugnp == null)
            {
                return NotFound();
            }

            return View(ugnp);
        }

        // POST: Ugnps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ugnp = await _context.Ugnp.FindAsync(id);
            _context.Ugnp.Remove(ugnp);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UgnpExists(int id)
        {
            return _context.Ugnp.Any(e => e.Id == id);
        }
    }
}

EbsTisbiBook.WebAppMVC/Controllers/Books/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EbsTisbiBook.WebAppMVC.Models;
using EbsTisbiBook.WebAppMVC.Models.Library;
using EbsTisbiBook.WebAppMVC.Models.Library.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Korzh.EasyQuery.Linq;
using Microsoft.AspNetCore.Authorization;

namespace EbsTisbiBook.WebAppMVC.Controllers.Books
{
    [Authorize(Roles = "User")]
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;

        public BooksController(LibraryContext libraryContext)
        {
            _context = libraryContext;
        }

        public async Task<IActionResult> List(int? pubhouse, int? author, int? pubyearMin, int? pubyearMax, string searchText, int page = 1,
            BooksSortState sortOrder = BooksSortState.PubyearAsc)
        {
            var pageSize = 4;   // количество элементов на странице

            //  фильтрация
            IQueryable<Book> books = _context.Books
                .Include(b => b.Pubhouse)
                .Include(a => a.Authors);

            if (pubhouse != null && pubhouse != 0)
            {
                books = books.Where(b => b.PubhouseId == pubhouse);
            }

            if (author != null && author != 0)
            {
                books = books.Where(b => b.Authors.Contains(
                    _context.Authors.FirstOrDefault(a => a.Id == author)));
            }

            pubyearMin ??= 0;
            pubyearMax ??= int.MaxValue;
            books = books.Where(b => b.Pubyear >= pubyearMin && b.Pubyear <= pubyearMax);

            // полнотекстовый поиск

            if (!string.IsNullOrEmpty(searchText))
            {
                books = books.FullTextSearchQuery(searchText);
            }

            // сортировка
            switch (sortOrder)
            {
                case BooksSortState.PubyearDesc:
                    books = books.OrderByDescending(b => b.Pubyear);
                    break;
                default:
                    books = books.OrderBy(b => b.Pubyear);
                    break;
            }

            var foundCount = books.Count();

            //  пагинация
            var count = await books.CountAsync();  //  общее к-во элементов
            var items = await books.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            BooksListViewModel viewModel = new BooksListViewModel
            {
                PageViewModel = pageViewModel,
                SortViewModel = new SortViewModel(sortOrder),
                FilterViewModel = new FilterViewModel(_context.Pubhouses.ToList(), pubhouse, _context.Authors.ToList(), author, searchText, pubyearMin, pubyearMax),
                Books = items,
                Count = foundCount
            };
            return View(viewModel);
        }

        public IActionResult Book(int id)
        {
            var model = _context.Books
                .Include(b => b.Pubhouse)
                .Include(a => a.Authors)
                .FirstOrDefault(b => b.Id == id);
            return View(model);
        }
    }
}

EbsTisbiBook.WebAppMVC/Views/Admin/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EbsTisbiBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EbsTisbiBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Books" asp-action="Index">Издания</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Authors" asp-action="Index">Авторы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Fgos" asp-action="Index">ФГОС</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Ugnp" asp-action="Index">УГНП</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Languages" asp-action="Index">Языки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pubhouses" asp-action="Index">Издетальства</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pubtypes" asp-action="Index">Типы издания</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialPurposes" asp-action="Index">Целевые назначения</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Пользователи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Roles" asp-action="Index">Роли</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">На главную</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EbsTisbiBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>